version: "3.9"
services:
  #Microsservice
  server:
    container_name: RinhaJava
    build: .
    environment:
      db_internal_url: "jdbc:postgresql://postgres:5432/postgres"
      db_user: "user"
      db_password: "password"
    ports:
      - "8081:8080"

  #Postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "10002:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"